/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Wallpaper } from "./Wallpaper";
import { WallpaperCountArgs } from "./WallpaperCountArgs";
import { WallpaperFindManyArgs } from "./WallpaperFindManyArgs";
import { WallpaperFindUniqueArgs } from "./WallpaperFindUniqueArgs";
import { DeleteWallpaperArgs } from "./DeleteWallpaperArgs";
import { WallpaperService } from "../wallpaper.service";
@graphql.Resolver(() => Wallpaper)
export class WallpaperResolverBase {
  constructor(protected readonly service: WallpaperService) {}

  async _wallpapersMeta(
    @graphql.Args() args: WallpaperCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Wallpaper])
  async wallpapers(
    @graphql.Args() args: WallpaperFindManyArgs
  ): Promise<Wallpaper[]> {
    return this.service.wallpapers(args);
  }

  @graphql.Query(() => Wallpaper, { nullable: true })
  async wallpaper(
    @graphql.Args() args: WallpaperFindUniqueArgs
  ): Promise<Wallpaper | null> {
    const result = await this.service.wallpaper(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Wallpaper)
  async deleteWallpaper(
    @graphql.Args() args: DeleteWallpaperArgs
  ): Promise<Wallpaper | null> {
    try {
      return await this.service.deleteWallpaper(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
